const translations = {
  en: {
    translation: {
      previous: "Previous",
      next: "Next",
      go_back: "Go back",
      es: "Spanish",
      de: "German",
      en: "English",
      it: "Italian",
      fr: "French",
      visit_profile: "View Github's profile",
      public_repos: "Public repos",
      public_gists: "Public gists",
      followers: "Followers",
      following: "Following",
      generic_api_error: "Ooops! An error has occurred retrieving data from Github API. Try again in a few minutes."
    },
  },
  es: {
    translation: {
      previous: "Anterior",
      next: "Siguiente",
      go_back: "Volver",
      es: "Español",
      de: "Alemán",
      en: "Inglés",
      it: "Italiano",
      fr: "Francés",
      visit_profile: "Ver el perfil de Github",
      public_repos: "Repos públicos",
      public_gists: "Gists públicos",
      followers: "Seguidores",
      following: "Siguiendo",
      generic_api_error: "Ooops! An error has occurred retrieving data from Github API. Try again in a few minutes."
    },
  },
  fr: {
    translation: {
      previous: "Précédent",
      next: "Suivant",
      go_back: "Revenir",
      es: "Espagnol",
      de: "Allemand",
      en: "Anglais",
      it: "italien",
      fr: "Français",
      visit_profile: "Voir le profil de Github",
      public_repos: "Dépôts publics",
      public_gists: "Gists publics",
      followers: "Suiveurs",
      following: "Suivant",
      generic_api_error: "Oups! Une erreur s'est produite lors de la récupération des données de l'API Github. Réessayez dans quelques minutes."
    },
  },
  de: {
    translation: {
      previous: "Zurückfahren",
      next: "Nächste",
      go_back: "Wiederkehren",
      es: "Spanisch",
      de: "Deutsch",
      en: "Englisch",
      it: "Italienisch",
      fr: "Französisch",
      visit_profile: "Githubs profil anzeigen",
      public_repos: "Öffentliche Repos",
      public_gists: "Öffentliche Gists",
      followers: "Anhänger",
      following: "Folgen",
      generic_api_error: "Ups! Beim Abrufen der Daten von der Github-API ist ein Fehler aufgetreten. Versuchen Sie es in wenigen Minuten erneut."
    },
  },
  it: {
    translation: {
      previous: "Indietro",
      next: "Avanti",
      go_back: "Ritorno",
      es: "spagnolo",
      de: "Tedesco",
      en: "Inglese",
      it: "italiano",
      fr: "Francese",
      visit_profile: "Visualizza il profilo di Github",
      public_repos: "Repository pubblici",
      public_gists: "Gists pubblici",
      followers: "Seguaci",
      following: "A seguire",
      generic_api_error: "Ops! Si è verificato un errore durante il recupero dei dati dall'API Github. Riprova tra qualche minuto."
    },
  },
};

export default translations;
